"""
inference/__init__.py
=====================
Core dataclasses for the OA detection inference pipeline.

Defines the structured output types produced during a full analysis run:

- ``RiskMarkerResult``  – per-marker status with confidence and provenance note.
- ``RiskMarkersReport`` – aggregation of all six OA risk marker assessments.
- ``OAAnalysisResult``  – top-level result object returned by :class:`OAPredictor`.

All results carry an explicit medical disclaimer and a
``requires_clinical_review = True`` flag to emphasise that no output from
this system replaces evaluation by a qualified radiologist or clinician.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field, asdict
from typing import Any, Dict, List, Optional

import numpy as np

# ---------------------------------------------------------------------------
# Re-export companion dataclasses so callers can import from a single place.
# ---------------------------------------------------------------------------
from preprocessing import PreprocessingResult  # noqa: F401
from models import ModelPrediction, ExplainabilityResult  # noqa: F401

# ---------------------------------------------------------------------------
# Medical disclaimer – included verbatim in every OAAnalysisResult
# ---------------------------------------------------------------------------
DISCLAIMER: str = (
    "RESEARCH / INVESTIGATIONAL USE ONLY. "
    "This output has been generated by an AI model and has NOT been validated "
    "for clinical diagnostic use. It does not constitute a medical diagnosis, "
    "prognosis, or treatment recommendation. All findings must be reviewed and "
    "interpreted by a qualified radiologist or treating clinician before any "
    "clinical decision is made. The developers accept no liability for decisions "
    "made on the basis of these outputs."
)


# ---------------------------------------------------------------------------
# RiskMarkerResult
# ---------------------------------------------------------------------------

@dataclass
class RiskMarkerResult:
    """Assessment of a single OA risk marker derived from model and image analysis.

    Attributes
    ----------
    status : str
        One of ``'detected'``, ``'possible'``, ``'uncertain'``, or
        ``'not_detected'``.  The boundary thresholds are set in
        ``configs/oa_model.yaml`` and applied inside
        :class:`~inference.risk_markers.RiskMarkerExtractor`.
    confidence : float
        Confidence in the status assignment, in the range ``[0, 1]``.
    source : str
        Either ``'model'`` (derived from deep-learning feature vector) or
        ``'image_analysis'`` (derived from classical computer-vision
        measurements).  In practice most markers combine both.
    note : str
        Brief human-readable explanation of how the status was determined,
        including any caveats about measurement reliability.

    .. warning::
        These assessments are **proxy estimates** produced by computer vision
        algorithms.  They are *not* equivalent to radiological findings from a
        qualified clinician and should never be used as such.
    """

    status: str        # 'detected' | 'possible' | 'uncertain' | 'not_detected'
    confidence: float  # [0, 1]
    source: str        # 'model' | 'image_analysis'
    note: str          # brief explanation / caveat

    def __post_init__(self) -> None:
        valid_statuses = {"detected", "possible", "uncertain", "not_detected"}
        if self.status not in valid_statuses:
            raise ValueError(
                f"Invalid status '{self.status}'. Must be one of {valid_statuses}."
            )
        if not (0.0 <= self.confidence <= 1.0):
            raise ValueError(
                f"Confidence must be in [0, 1]; got {self.confidence}."
            )
        valid_sources = {"model", "image_analysis"}
        if self.source not in valid_sources:
            raise ValueError(
                f"Invalid source '{self.source}'. Must be one of {valid_sources}."
            )

    def to_dict(self) -> Dict[str, Any]:
        """Serialise to a plain dictionary."""
        return asdict(self)


# ---------------------------------------------------------------------------
# RiskMarkersReport
# ---------------------------------------------------------------------------

@dataclass
class RiskMarkersReport:
    """Aggregated assessment of all six canonical OA risk markers.

    Each field is a :class:`RiskMarkerResult` produced by
    :class:`~inference.risk_markers.RiskMarkerExtractor`.

    Attributes
    ----------
    joint_space_narrowing : RiskMarkerResult
        Proxy for reduced joint-space width inferred from intensity analysis
        in the central joint region.
    osteophytes : RiskMarkerResult
        Proxy for bone-spur formation estimated via edge-density analysis near
        bone margins.
    subchondral_sclerosis : RiskMarkerResult
        Proxy for increased subchondral bone density via intensity histogram
        analysis near the joint line.
    bone_deformity : RiskMarkerResult
        Proxy for gross bone shape irregularities estimated via contour
        analysis.
    alignment_abnormality : RiskMarkerResult
        Proxy for mechanical-axis deviation estimated via Hough-line analysis.
        **Highly unreliable without calibrated full-limb radiographs.**
    cystic_changes : RiskMarkerResult
        Proxy for subchondral cyst presence estimated via blob detection.

    .. note::
        All markers are proxies from classical CV combined with deep-learning
        scores.  None are clinically validated measurements.
    """

    joint_space_narrowing: RiskMarkerResult
    osteophytes: RiskMarkerResult
    subchondral_sclerosis: RiskMarkerResult
    bone_deformity: RiskMarkerResult
    alignment_abnormality: RiskMarkerResult
    cystic_changes: RiskMarkerResult

    def to_dict(self) -> Dict[str, Dict[str, Any]]:
        """Serialise all markers to a nested dictionary."""
        return {
            "joint_space_narrowing": self.joint_space_narrowing.to_dict(),
            "osteophytes": self.osteophytes.to_dict(),
            "subchondral_sclerosis": self.subchondral_sclerosis.to_dict(),
            "bone_deformity": self.bone_deformity.to_dict(),
            "alignment_abnormality": self.alignment_abnormality.to_dict(),
            "cystic_changes": self.cystic_changes.to_dict(),
        }

    def detected_markers(self) -> List[str]:
        """Return names of markers with status ``'detected'`` or ``'possible'``."""
        markers = self.to_dict()
        return [
            name
            for name, result in markers.items()
            if result["status"] in {"detected", "possible"}
        ]


# ---------------------------------------------------------------------------
# OAAnalysisResult
# ---------------------------------------------------------------------------

@dataclass
class OAAnalysisResult:
    """Top-level result object returned by :class:`~inference.predictor.OAPredictor`.

    Aggregates every stage of the analysis pipeline into a single serialisable
    container.

    Attributes
    ----------
    preprocessing : PreprocessingResult
        Output of the preprocessing stage (from ``preprocessing/``).
    prediction : ModelPrediction
        Raw model prediction (from ``models/``).
    risk_markers : RiskMarkersReport
        Structured risk-marker assessments.
    explainability : ExplainabilityResult
        Grad-CAM (or equivalent) heatmap result (from ``models/``).
    kl_grade : Optional[int]
        Kellgren–Lawrence grade.  **Always** ``None`` unless a model
        specifically fine-tuned for KL grading is loaded.
    kl_grade_confidence : Optional[float]
        Confidence for the KL grade prediction.  ``None`` when
        ``kl_grade`` is ``None``.
    requires_clinical_review : bool
        Always ``True``.  Present to make the requirement machine-readable.
    warnings : List[str]
        Accumulated warnings from all pipeline stages.
    study_type : str
        Imaging modality / study type (e.g. ``'xray'``, ``'mri'``).
    joint_type : str
        Anatomical joint analysed (e.g. ``'knee'``, ``'hip'``, ``'hand'``).
    timestamp : str
        ISO-8601 UTC timestamp when the analysis was run.
    model_name : str
        Name of the model used.
    model_version : str
        Version string of the model used.
    disclaimer : str
        Verbatim medical disclaimer.  Populated automatically from the
        module-level :data:`DISCLAIMER` constant.

    .. warning::
        ``requires_clinical_review`` is always ``True``.  This field exists
        for machine-readable enforcement; it must **never** be set to
        ``False`` by downstream code.
    """

    preprocessing: PreprocessingResult
    prediction: ModelPrediction
    risk_markers: RiskMarkersReport
    explainability: ExplainabilityResult
    kl_grade: Optional[int]
    kl_grade_confidence: Optional[float]
    requires_clinical_review: bool
    warnings: List[str]
    study_type: str
    joint_type: str
    timestamp: str
    model_name: str
    model_version: str
    disclaimer: str = field(default=DISCLAIMER)

    def __post_init__(self) -> None:
        # Enforce clinical review requirement – must never be overridden.
        if not self.requires_clinical_review:
            raise ValueError(
                "requires_clinical_review must always be True. "
                "This system is not validated for autonomous clinical decisions."
            )
        # KL grade is only valid when explicitly fine-tuned.
        if self.kl_grade is not None and not self.prediction.requires_finetuning:
            import warnings as _warnings
            _warnings.warn(
                "kl_grade is set but the model does not appear to be fine-tuned "
                "for KL grading. Treat this value with extreme caution.",
                UserWarning,
                stacklevel=2,
            )
        # Ensure disclaimer is always the canonical text.
        self.disclaimer = DISCLAIMER

    # ------------------------------------------------------------------
    # Serialisation helpers
    # ------------------------------------------------------------------

    def to_dict(self) -> Dict[str, Any]:
        """Serialise the full result to a JSON-compatible dictionary.

        Arrays (``np.ndarray``) are converted to lists; ``None`` values are
        preserved.  The returned dictionary is safe to pass to
        ``json.dumps``.

        Returns
        -------
        Dict[str, Any]
            Fully serialised result.
        """
        def _convert(obj: Any) -> Any:
            if isinstance(obj, np.ndarray):
                return obj.tolist()
            if isinstance(obj, dict):
                return {k: _convert(v) for k, v in obj.items()}
            if isinstance(obj, list):
                return [_convert(i) for i in obj]
            return obj

        preprocessing_dict: Dict[str, Any] = {
            "image_path": self.preprocessing.image_path,
            "modality": self.preprocessing.modality,
            "study_type": self.preprocessing.study_type,
            "metadata": _convert(self.preprocessing.metadata),
            "warnings": self.preprocessing.warnings,
            "roi_bbox": self.preprocessing.roi_bbox,
        }

        prediction_dict: Dict[str, Any] = {
            "oa_score": self.prediction.oa_score,
            "confidence_level": self.prediction.confidence_level,
            "raw_probabilities": self.prediction.raw_probabilities,
            "model_name": self.prediction.model_name,
            "model_version": self.prediction.model_version,
            "requires_finetuning": self.prediction.requires_finetuning,
        }

        explainability_dict: Dict[str, Any] = {
            "method": self.explainability.method,
            "target_layer": self.explainability.target_layer,
            "warning": self.explainability.warning,
        }

        return {
            "timestamp": self.timestamp,
            "joint_type": self.joint_type,
            "study_type": self.study_type,
            "model_name": self.model_name,
            "model_version": self.model_version,
            "requires_clinical_review": self.requires_clinical_review,
            "disclaimer": self.disclaimer,
            "kl_grade": self.kl_grade,
            "kl_grade_confidence": self.kl_grade_confidence,
            "warnings": self.warnings,
            "preprocessing": preprocessing_dict,
            "prediction": prediction_dict,
            "risk_markers": self.risk_markers.to_dict(),
            "explainability": explainability_dict,
        }

    def to_json(self, indent: int = 2) -> str:
        """Serialise to a JSON string.

        Parameters
        ----------
        indent : int
            JSON indentation level.

        Returns
        -------
        str
            JSON-formatted string.
        """
        return json.dumps(self.to_dict(), indent=indent)

    def summary(self) -> str:
        """Return a concise human-readable summary string."""
        detected = self.risk_markers.detected_markers()
        kl_str = (
            f"KL Grade: {self.kl_grade} (conf: {self.kl_grade_confidence:.2f})"
            if self.kl_grade is not None
            else "KL Grade: N/A (model not fine-tuned for KL grading)"
        )
        return (
            f"OA Analysis Summary [{self.timestamp}]\n"
            f"  Joint     : {self.joint_type} | Study: {self.study_type}\n"
            f"  Model     : {self.model_name} v{self.model_version}\n"
            f"  OA Score  : {self.prediction.oa_score:.4f} "
            f"({self.prediction.confidence_level})\n"
            f"  {kl_str}\n"
            f"  Markers   : {', '.join(detected) if detected else 'None prominent'}\n"
            f"  Warnings  : {len(self.warnings)}\n"
            f"  ⚠  {self.disclaimer[:80]}…"
        )


__all__ = [
    "DISCLAIMER",
    "RiskMarkerResult",
    "RiskMarkersReport",
    "OAAnalysisResult",
    # Re-exported from sibling packages for convenience
    "PreprocessingResult",
    "ModelPrediction",
    "ExplainabilityResult",
]
